### ISSUE TITLE
Maybe a memory leak

### ISSUE THREAD

**Issue by Neo-X** [xbpeng/TerrainRL#3]
Might be coming from tSegment::Init()

**Comment by Neo-X** [comment]
[memory leaks.txt](https://github.com/xbpeng/TerrainRL/files/65089/memory.leaks.txt)

**Comment by xbpeng** [comment]
thanks for the info. In your change list you modified mShape.reset() to delete mShape.release(). Is there a difference? I thought reset will free the pointer object if nothing else owns it.

**Comment by Neo-X** [comment]
That is correct, as far as I know. I was just trying different things in case Linux only had partial support for the C++11 pointer types.

**Comment by Neo-X** [comment]
One issue found was the profiling in Bullet look for "BT_PROFILE", better yet "BT_NO_PROFILE" and disable the profiling.

**Comment by xbpeng** [comment]
Nice!
