### ISSUE TITLE
Detecting continuous contact

### ISSUE THREAD

**Issue by Neo-X** [xbpeng/TerrainRL#4]
This issue is causing problems with the hopper again. I have been analyzing the collision detection code and it seems to be a result of the numerical constraint to keep the rigid bodies from penetrating. On an initial hit the bodies may penetrate but after this the constraint solver will make sure the bodies do not penetrate. I think a possible solution is to classify collision as Bullet generating a manifold that is withing a small positive distance.

**Comment by Neo-X** [comment]
This has worked wonderfully. If you don't see any issues with it effecting your controllers I will commit the patch.

**Comment by xbpeng** [comment]
nice, thanks for looking into that. it's hard to say how this might effect the dog, but check it in and i'll take a look
